### ISSUE TITLE
Add Databricks Units (DBU) to VM sizes

### ISSUE THREAD

**Issue by nathan-gs** [kvaes/azure-vmchooser-frontend-v3#13]
It would be very useful to add the Azure Databricks DBUs to the VMs, because this is a major cost driver. 

https://azure.microsoft.com/en-us/pricing/details/databricks/

**Comment by kvaes** [comment]
Moved to "cental" repo for visibility.
Added appropriate tags

**Comment by kvaes** [comment]
@nathan-gs  ; Any idea if I can scrape that data from somewhere? That would help me ... by a lot. :)

**Comment by kvaes** [comment]
For future reference ; https://azure.microsoft.com/api/v2/pricing/databricks/calculator/

**Comment by kvaes** [comment]
Implemented for  VmChooser ; https://www.vmchooser.com/vmchooser 
BulkUploader : *pending*
