### ISSUE TITLE
Allow Option to overwrite recommended VM

### ISSUE THREAD

**Issue by srakesh28** [kvaes/azure-vmchooser-frontend-v3#18]
Would be great if you can allow the option to override the VM that was recommended by default, sometimes it's required to override VM that recommended by the Bulk uploader to maintain consistency across many regions we are mapping. Please consider this request.

**Comment by kvaes** [comment]
And how do you see the override functioning? Having a line per VM that already states what VM size it should be, and then checking the prices for that VM size?

**Comment by kvaes** [comment]
Close till more info is provided
